username:
  type: string
  default: ""
  description:
      en: "Show buttons only to the admin with this username. "
show_for_admin:
  type: bool
  default: false
  description:
    en: "Hide all alert banners and notifications"
show_for_moderator:
  type: bool
  default: false
  description:
    en: "Hide all alert banners and notifications"
Header_links:
  type: list
  default: "Settings,cog,/admin/site_settings,vdo,self|Customize,paint-brush,/admin/customize/themes,vdo,self|Texts,paragraph,/admin/customize/site_texts,vdo,self"
  description:
    en: "Comma delimited in this order: <br>
      <b>title, icon, URL, view, target</b>
      <br>
      <br>
      <b>title</b>: the desired title you want the link to have (when hovered). <br>
      <b>icon</b>: the icon you want the link to have. <br>
      <b>View</b>:
      <ul>
      <li>visible on both desktop and mobile devices (vdm)</li>
      <li>Desktop only (vdo).</li>
      <li>mobile only (vmo).</li>
      </ul>
      <b>URL</b>: the desired URL you want the link to point to. <br>
      <b>Target</b>: same tab (self) or new tab (blank)."
hide_alerts:
  type: bool
  default: false
  description:
    en: "Hide all alert banners and notifications"
Svg_icons:
  type: "list"
  list_type: "compact"
  default: "paint-brush|paragraph"
  description:
    en: "Include FontAwesome 5 icon classes for each icon used in the list."
